#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : sqlite-autoconf
Version  : 3120000
Release  : 34
URL      : http://www.sqlite.org/2016/sqlite-autoconf-3120000.tar.gz
Source0  : http://www.sqlite.org/2016/sqlite-autoconf-3120000.tar.gz
Summary  : SQL database engine
Group    : Development/Tools
License  : Public-Domain
Requires: sqlite-autoconf-bin
Requires: sqlite-autoconf-lib
Requires: sqlite-autoconf-doc
BuildRequires : automake
BuildRequires : automake-dev
BuildRequires : gettext-bin
BuildRequires : libtool
BuildRequires : libtool-dev
BuildRequires : m4
BuildRequires : pkg-config-dev
BuildRequires : readline-dev
Patch1: flags.patch
Patch2: defaults.patch
Patch3: walmode.patch

%description
This is the SQLite extension for Tcl using the Tcl Extension
Architecture (TEA).  For additional information on SQLite see

%package bin
Summary: bin components for the sqlite-autoconf package.
Group: Binaries

%description bin
bin components for the sqlite-autoconf package.


%package dev
Summary: dev components for the sqlite-autoconf package.
Group: Development
Requires: sqlite-autoconf-lib
Requires: sqlite-autoconf-bin
Provides: sqlite-autoconf-devel

%description dev
dev components for the sqlite-autoconf package.


%package doc
Summary: doc components for the sqlite-autoconf package.
Group: Documentation

%description doc
doc components for the sqlite-autoconf package.


%package lib
Summary: lib components for the sqlite-autoconf package.
Group: Libraries

%description lib
lib components for the sqlite-autoconf package.


%prep
%setup -q -n sqlite-autoconf-3120000
%patch1 -p1
%patch2 -p1
%patch3 -p1

%build
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -fno-semantic-interposition -flto -falign-functions=32 -O3 "
export FCFLAGS="$CFLAGS -fno-semantic-interposition -flto -falign-functions=32 -O3 "
export FFLAGS="$CFLAGS -fno-semantic-interposition -flto -falign-functions=32 -O3 "
export CXXFLAGS="$CXXFLAGS -fno-semantic-interposition -flto -falign-functions=32 -O3 "
%reconfigure --disable-static
make V=1  %{?_smp_mflags} -j1

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/sqlite3

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
